// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;


class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAcc4csdVxpBDHJSDvYfxk8Tc7_nmVQiaY',
    appId: '1:301566690169:web:174278695e7e77a55325a8',
    messagingSenderId: '301566690169',
    projectId: 'push-notification-8c49b',
    authDomain: 'push-notification-8c49b.firebaseapp.com',
    storageBucket: 'push-notification-8c49b.firebasestorage.app',
    measurementId: 'G-35EEBV6FGK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCK5p1ui7jlrwKUXvgef7fmnbUyvXtfeOs',
    appId: '1:301566690169:android:b00eba391b2d1e905325a8',
    messagingSenderId: '301566690169',
    projectId: 'push-notification-8c49b',
    storageBucket: 'push-notification-8c49b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAgRp52JSErkvSzEWLmaAMw3IZPPcfokjA',
    appId: '1:301566690169:ios:364aa63f889a18115325a8',
    messagingSenderId: '301566690169',
    projectId: 'push-notification-8c49b',
    storageBucket: 'push-notification-8c49b.firebasestorage.app',
    iosBundleId: 'com.digivity.etab.digivityadminapp',
  );

}